//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMINISTER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADMINISTER()
        {
            this.COLLECTION_ACTIVITY = new HashSet<COLLECTION_ACTIVITY>();
            this.COMMENTREVIEW = new HashSet<COMMENTREVIEW>();
            this.EVENTCHECK = new HashSet<EVENTCHECK>();
        }
    
        public int ADMINISTER_ID { get; set; }
        public System.DateTime ADMINISTER_WORKDAY { get; set; }
        public string ADMINISTER_EMAIL { get; set; }
        public string ADMINISTER_NAME { get; set; }
        public string ADMINISTER_PHONE { get; set; }
        public string ADMINISTER_PASSWORD { get; set; }
        public string ADMINISTER_PROFILE { get; set; }
        public string ADMINISTER_STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COLLECTION_ACTIVITY> COLLECTION_ACTIVITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENTREVIEW> COMMENTREVIEW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENTCHECK> EVENTCHECK { get; set; }
    }
}
