//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADVICE
    {
        public int ADVICE_ID { get; set; }
        public int DOCTOR_ID { get; set; }
        public int ELDERLY_ID { get; set; }
        public string ADVICE_CONTENT { get; set; }
        public bool ADVICE_LABEL { get; set; }
        public System.DateTime ADVICE_DATE { get; set; }
        public bool ADVICE_VISABLE { get; set; }
    
        public virtual APPUSER APPUSER { get; set; }
        public virtual COMMUNITY_DOCTOR COMMUNITY_DOCTOR { get; set; }
        public virtual THEELDERLY THEELDERLY { get; set; }
    }
}
