//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPUSER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public APPUSER()
        {
            this.ADVICE = new HashSet<ADVICE>();
            this.DRUG_LOG = new HashSet<DRUG_LOG>();
            this.DRUG_LOG1 = new HashSet<DRUG_LOG>();
        }
    
        public int USER_ID { get; set; }
        public string USER_EMAIL { get; set; }
        public string USER_PHONE { get; set; }
        public string USER_PASSWORD { get; set; }
        public string USER_NAME { get; set; }
        public string USER_PROFILE { get; set; }
        public System.DateTime USER_CREATETIME { get; set; }
        public Nullable<System.DateTime> USER_BIRTHDAY { get; set; }
        public string USER_GENDER { get; set; }
        public string USER_STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADVICE> ADVICE { get; set; }
        public virtual CARETAKER CARETAKER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRUG_LOG> DRUG_LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRUG_LOG> DRUG_LOG1 { get; set; }
    }
}
