//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARETAKER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARETAKER()
        {
            this.APPORDER = new HashSet<APPORDER>();
            this.CARE = new HashSet<CARE>();
            this.COLLECTION_ACTIVITY = new HashSet<COLLECTION_ACTIVITY>();
            this.COMMENTTHUMBSUP = new HashSet<COMMENTTHUMBSUP>();
            this.COMMENTTHUMBSUP1 = new HashSet<COMMENTTHUMBSUP>();
            this.DISCUSSION = new HashSet<DISCUSSION>();
            this.JOIN_ACTIVITY = new HashSet<JOIN_ACTIVITY>();
            this.PUBLICATION_DISCUSSION = new HashSet<PUBLICATION_DISCUSSION>();
            this.THUMBSUP_ACTIVITY = new HashSet<THUMBSUP_ACTIVITY>();
        }
    
        public int CARETAKER_ID { get; set; }
        public decimal CARETAKER_EXPERIENCE { get; set; }
        public decimal CARETAKER_TYPE { get; set; }
        public string CARETAKER_PHONE { get; set; }
        public string CARETAKER_PASSWORD { get; set; }
        public string CARETAKER_NAME { get; set; }
        public string CARETAKER_PROFILE { get; set; }
        public System.DateTime CARETAKER_CREATETIME { get; set; }
        public string CARETAKER_GENDER { get; set; }
        public string CARETAKER_STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPORDER> APPORDER { get; set; }
        public virtual APPUSER APPUSER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARE> CARE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COLLECTION_ACTIVITY> COLLECTION_ACTIVITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENTTHUMBSUP> COMMENTTHUMBSUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENTTHUMBSUP> COMMENTTHUMBSUP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISCUSSION> DISCUSSION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOIN_ACTIVITY> JOIN_ACTIVITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUBLICATION_DISCUSSION> PUBLICATION_DISCUSSION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THUMBSUP_ACTIVITY> THUMBSUP_ACTIVITY { get; set; }
    }
}
