//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECK_RECORD
    {
        public int CHECK_ID { get; set; }
        public int ELDERLY_ID { get; set; }
        public int DOCTOR_ID { get; set; }
        public Nullable<decimal> BODY_MASS_INDEX { get; set; }
        public Nullable<decimal> DIASTOLIC_PRESSURE { get; set; }
        public Nullable<decimal> SYSTOLIC_PRESSURE { get; set; }
        public Nullable<decimal> HEART_RATE { get; set; }
        public Nullable<decimal> BLOOD_OXYGEN_SATURATION { get; set; }
        public Nullable<decimal> BLOOD_LIPIDS { get; set; }
        public string CHECK_NAME { get; set; }
        public string CHECK_RESULT { get; set; }
        public decimal CHECK_FEE { get; set; }
        public System.DateTime CHECK_DATE { get; set; }
    
        public virtual THEELDERLY THEELDERLY { get; set; }
        public virtual COMMUNITY_DOCTOR COMMUNITY_DOCTOR { get; set; }
    }
}
