//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMENTREVIEW
    {
        public int ADMINISTRATOR_ID { get; set; }
        public int ACTIVITY_ID { get; set; }
        public int COMMENT_ID { get; set; }
        public System.DateTime REVIEW_DATE { get; set; }
        public string RESULT { get; set; }
    
        public virtual ADMINISTER ADMINISTER { get; set; }
        public virtual EVENT EVENT { get; set; }
    }
}
