//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMUNITY_DOCTOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMMUNITY_DOCTOR()
        {
            this.CHECK_RECORD = new HashSet<CHECK_RECORD>();
            this.COLLECTION_ACTIVITY = new HashSet<COLLECTION_ACTIVITY>();
            this.COMMENTTHUMBSUP = new HashSet<COMMENTTHUMBSUP>();
            this.COMMENTTHUMBSUP1 = new HashSet<COMMENTTHUMBSUP>();
            this.JOIN_ACTIVITY = new HashSet<JOIN_ACTIVITY>();
            this.THUMBSUP_ACTIVITY = new HashSet<THUMBSUP_ACTIVITY>();
            this.ADVICE = new HashSet<ADVICE>();
            this.DRUG_LOG = new HashSet<DRUG_LOG>();
        }
    
        public int COMMUNITY_DOCTOR_ID { get; set; }
        public string COMMUNITY_DOCTOR_CITY { get; set; }
        public string COMMUNITY_DOCTOR_HOSPITAL { get; set; }
        public string COMMUNITY_DOCTOR_DEPARTMENT { get; set; }
        public string COMMUNITY_EMAIL { get; set; }
        public string COMMUNITY_PHONE { get; set; }
        public string COMMUNITY_PASSWORD { get; set; }
        public string COMMUNITY_NAME { get; set; }
        public string COMMUNITY_STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHECK_RECORD> CHECK_RECORD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COLLECTION_ACTIVITY> COLLECTION_ACTIVITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENTTHUMBSUP> COMMENTTHUMBSUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENTTHUMBSUP> COMMENTTHUMBSUP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOIN_ACTIVITY> JOIN_ACTIVITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THUMBSUP_ACTIVITY> THUMBSUP_ACTIVITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADVICE> ADVICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRUG_LOG> DRUG_LOG { get; set; }
    }
}
