//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRUG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DRUG()
        {
            this.DRUG_LOG = new HashSet<DRUG_LOG>();
            this.DRUG_STORE = new HashSet<DRUG_STORE>();
            this.DRUGDIRECTORY = new HashSet<DRUGDIRECTORY>();
            this.PURCHASE = new HashSet<PURCHASE>();
        }
    
        public string DRUG_ID { get; set; }
        public string DRUG_NAME { get; set; }
        public string DRUG_DOSAGE_FORM { get; set; }
        public string DRUG_USAGE { get; set; }
        public string DRUG_CONTRAINDICATIONS { get; set; }
        public string DRUG_EFFECTS { get; set; }
        public string MANUFACTURER { get; set; }
        public decimal PRESCRIPTION { get; set; }
        public decimal STATE { get; set; }
        public string MANAGER_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_TIME { get; set; }
        public Nullable<decimal> MIN_INVENTORY_QUANTITY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRUG_LOG> DRUG_LOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRUG_STORE> DRUG_STORE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRUGDIRECTORY> DRUGDIRECTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PURCHASE> PURCHASE { get; set; }
    }
}
