//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRUG_LOG
    {
        public int ELDERLY_ID { get; set; }
        public string DRUG_ID { get; set; }
        public System.DateTime START_DATE { get; set; }
        public string DOSAGE { get; set; }
        public decimal DOSAGE_FREQUENCY { get; set; }
        public string DOSAGE_METHOD { get; set; }
        public decimal DOSAGE_DURATION { get; set; }
        public int DOCTOR_ID { get; set; }
    
        public virtual APPUSER APPUSER { get; set; }
        public virtual APPUSER APPUSER1 { get; set; }
        public virtual DRUG DRUG { get; set; }
        public virtual COMMUNITY_DOCTOR COMMUNITY_DOCTOR { get; set; }
        public virtual THEELDERLY THEELDERLY { get; set; }
    }
}
