//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRUG_STORE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DRUG_STORE()
        {
            this.PURCHASE = new HashSet<PURCHASE>();
        }
    
        public string DRUG_ID { get; set; }
        public System.DateTime MANUFACTURE_DATE { get; set; }
        public System.DateTime EXPIRY_DATE { get; set; }
        public decimal INVENTORY_QUANTITY { get; set; }
        public decimal PRICE { get; set; }
    
        public virtual DRUG DRUG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PURCHASE> PURCHASE { get; set; }
    }
}
