//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ELDERLY_EMERGENCY_CONTECT
    {
        public int ELDERLY_ID { get; set; }
        public string ELDERLY_EMERGENCY_NAME { get; set; }
        public long ELDERLY_EMERGENCY_PHONE { get; set; }
    
        public virtual THEELDERLY THEELDERLY { get; set; }
    }
}
