//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTCHECK
    {
        public int EVENT_ID { get; set; }
        public Nullable<int> ADMINISTRATOR_ID { get; set; }
        public System.DateTime SUMMIT_DATE { get; set; }
        public Nullable<System.DateTime> REVIEW_DATE { get; set; }
        public string REVIEW_RESULT { get; set; }
        public string REVIEW_ADVICE { get; set; }
    
        public virtual ADMINISTER ADMINISTER { get; set; }
        public virtual EVENT EVENT { get; set; }
    }
}
