//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMINISTER> ADMINISTER { get; set; }
        public virtual DbSet<ADVICE> ADVICE { get; set; }
        public virtual DbSet<APPORDER> APPORDER { get; set; }
        public virtual DbSet<APPUSER> APPUSER { get; set; }
        public virtual DbSet<CARE> CARE { get; set; }
        public virtual DbSet<CARETAKER> CARETAKER { get; set; }
        public virtual DbSet<CHECK_RECORD> CHECK_RECORD { get; set; }
        public virtual DbSet<COLLECTION_ACTIVITY> COLLECTION_ACTIVITY { get; set; }
        public virtual DbSet<COMMENTREVIEW> COMMENTREVIEW { get; set; }
        public virtual DbSet<COMMENTTHUMBSUP> COMMENTTHUMBSUP { get; set; }
        public virtual DbSet<COMMUNITY_DOCTOR> COMMUNITY_DOCTOR { get; set; }
        public virtual DbSet<DISCUSSION> DISCUSSION { get; set; }
        public virtual DbSet<DRUG> DRUG { get; set; }
        public virtual DbSet<DRUG_LOG> DRUG_LOG { get; set; }
        public virtual DbSet<DRUG_STORE> DRUG_STORE { get; set; }
        public virtual DbSet<DRUGDIRECTORY> DRUGDIRECTORY { get; set; }
        public virtual DbSet<ELDERLY_EMERGENCY_CONTECT> ELDERLY_EMERGENCY_CONTECT { get; set; }
        public virtual DbSet<EVENT> EVENT { get; set; }
        public virtual DbSet<EVENTCHECK> EVENTCHECK { get; set; }
        public virtual DbSet<JOIN_ACTIVITY> JOIN_ACTIVITY { get; set; }
        public virtual DbSet<MEDICAL_HISTORY> MEDICAL_HISTORY { get; set; }
        public virtual DbSet<PHARMACY_ADMIN> PHARMACY_ADMIN { get; set; }
        public virtual DbSet<PUBLICATION_DISCUSSION> PUBLICATION_DISCUSSION { get; set; }
        public virtual DbSet<PURCHASE> PURCHASE { get; set; }
        public virtual DbSet<REPLYCOMMENT> REPLYCOMMENT { get; set; }
        public virtual DbSet<THEELDERLY> THEELDERLY { get; set; }
        public virtual DbSet<THUMBSUP_ACTIVITY> THUMBSUP_ACTIVITY { get; set; }
    }
}
