//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHARMACY_ADMIN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHARMACY_ADMIN()
        {
            this.PURCHASE = new HashSet<PURCHASE>();
        }
    
        public int PA_ID { get; set; }
        public string PA_CERTIFICATE { get; set; }
        public string PA_EMAIL { get; set; }
        public string PA_PHONE { get; set; }
        public string PA_PASSWORD { get; set; }
        public string PA_NAME { get; set; }
        public string PA_PROFILE { get; set; }
        public string PA_GENDER { get; set; }
        public System.DateTime PA_CREATETIME { get; set; }
        public decimal PA_EXPERIENCE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PURCHASE> PURCHASE { get; set; }
    }
}
