//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PURCHASE
    {
        public int PA_ID { get; set; }
        public string DRUG_ID { get; set; }
        public System.DateTime MANUFACTURE_DATE { get; set; }
        public System.DateTime PURCHASE_TIME { get; set; }
        public string PURCHASE_TYPE { get; set; }
        public decimal PURCHASE_NUM { get; set; }
        public decimal PURCHASE_PRICE { get; set; }
    
        public virtual DRUG DRUG { get; set; }
        public virtual DRUG_STORE DRUG_STORE { get; set; }
        public virtual PHARMACY_ADMIN PHARMACY_ADMIN { get; set; }
    }
}
