//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPERVISOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUPERVISOR()
        {
            this.THEELDERLY = new HashSet<THEELDERLY>();
        }
    
        public int SUPERVISOR_ID { get; set; }
        public string SUPERVISOR_PASSWORD { get; set; }
        public string SUPERVISOR_PHONE { get; set; }
        public string SUPERVISOR_NAME { get; set; }
        public string SUPERVISOR_PROFILE { get; set; }
        public System.DateTime SUPERVISOR_CREATE_TIME { get; set; }
        public string SUPERVISOR_GENDER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THEELDERLY> THEELDERLY { get; set; }
    }
}
