//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THEELDERLY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THEELDERLY()
        {
            this.APPORDER = new HashSet<APPORDER>();
            this.CARE = new HashSet<CARE>();
            this.CHECK_RECORD = new HashSet<CHECK_RECORD>();
            this.COLLECTION_ACTIVITY = new HashSet<COLLECTION_ACTIVITY>();
            this.COMMENTTHUMBSUP = new HashSet<COMMENTTHUMBSUP>();
            this.COMMENTTHUMBSUP1 = new HashSet<COMMENTTHUMBSUP>();
            this.DISCUSSION = new HashSet<DISCUSSION>();
            this.DRUGDIRECTORY = new HashSet<DRUGDIRECTORY>();
            this.JOIN_ACTIVITY = new HashSet<JOIN_ACTIVITY>();
            this.MEDICAL_HISTORY = new HashSet<MEDICAL_HISTORY>();
            this.PUBLICATION_DISCUSSION = new HashSet<PUBLICATION_DISCUSSION>();
            this.THUMBSUP_ACTIVITY = new HashSet<THUMBSUP_ACTIVITY>();
            this.ADVICE = new HashSet<ADVICE>();
        }
    
        public int ELDERLY_ID { get; set; }
        public string ELDERLY_ADDRESS { get; set; }
        public string ELDERLY_PASSWORD { get; set; }
        public string ELDERLY_PHONE { get; set; }
        public string ELDERLY_NAME { get; set; }
        public string ELDERLY_PROFILE { get; set; }
        public System.DateTime ELDERLY_BIRTHDAY { get; set; }
        public string ELDERLY_STATUS { get; set; }
        public string ELDERLY_GENDER { get; set; }
        public System.DateTime ELDERLY_CREATE_TIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPORDER> APPORDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CARE> CARE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHECK_RECORD> CHECK_RECORD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COLLECTION_ACTIVITY> COLLECTION_ACTIVITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENTTHUMBSUP> COMMENTTHUMBSUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENTTHUMBSUP> COMMENTTHUMBSUP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DISCUSSION> DISCUSSION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DRUGDIRECTORY> DRUGDIRECTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JOIN_ACTIVITY> JOIN_ACTIVITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MEDICAL_HISTORY> MEDICAL_HISTORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PUBLICATION_DISCUSSION> PUBLICATION_DISCUSSION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THUMBSUP_ACTIVITY> THUMBSUP_ACTIVITY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ADVICE> ADVICE { get; set; }
        public virtual ELDERLY_EMERGENCY_CONTECT ELDERLY_EMERGENCY_CONTECT { get; set; }
    }
}
